import type { Metadata } from "next";

import "./globals.css";
import NavBar from "./Components/NavBar";
import {Assistant} from 'next/font/google'
import Footer from "./Sections/Footer";
import { Toaster } from "@/components/ui/toaster"


export const assistant = Assistant({subsets: ['latin']})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${assistant.className} antialiased bg-backgroundApp`}
      >
        <NavBar />
        {children}
        <Footer/>
        <Toaster />
      </body>
    </html>
  );
}
